### ISSUE TITLE
Develop a generic CSDS client

### ISSUE THREAD

**Issue by fuqianggao** [envoyproxy/envoy-tools#9]
[Client status discovery service (CSDS)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/status/v3/csds.proto) is intended to be an API to query the status of xDS clients from control planes. 

A generic CSDS client can be used to connect to control planes that support the CSDS API and aid the debug of service mesh deployment where a large number of xDS clients connect to the control plane.

**Comment by fuqianggao** [comment]
@Rainton plans to work on this.

**Comment by mattklein123** [comment]
cc @danielhochman this is also relevant to Clutch. If this is written in Go it would be worth collaborating.

**Comment by fuqianggao** [comment]
@mattklein123 Yes, the plan is to write it in Go. What is Clutch? @danielhochman

**Comment by fuqianggao** [comment]
@mattklein123 Could you please assign this to @Rainton?

**Comment by dio** [comment]
The first attempt of it is merged. I think this one can be closed and we can create separate issues for specific requirements/enhancements/bugs/etc on this.
